### ISSUE TITLE
Not sekmeleri hatası

### ISSUE THREAD

**Issue by yilmazmuhammed** [eminfedar/widgetci#13]
3 farklı sekme açıp her birine farklı yazı yazdım. Ardından denemek için widgetci uygulamasından yeniledim, sıkıntı olmadı. Daha sonra uygulamadan Note'u kapatıp geri açtım, 3 sekmede de ilk sekmedeki yazı yazıyordu, sekme isimleri ise doğruydu.

Yani Note'u kapatıp geri açınca ilk sekme dışındaki sekmelerden yazılar siliniyor.

**Comment by eminfedar** [comment]
Evet çok ilginç, hemen bakıyorum.

**Comment by eminfedar** [comment]
**[Bu commit](https://github.com/eminfedar/widgetci/commit/8abafcce0a92095168f13ab2142f672eaf4545a0) ile düzeltildi.**

Note widgetinizi düzeltmek için [buradaki](https://github.com/eminfedar/widgetci/blob/dev-unstable/widgetci/defaultwidgets/Note/main.qml) dosyayı alıp eskisinin yerine koyabilirsiniz.

Geri bildirimleriniz için teşekkürler :) 👍

**Comment by yilmazm** [comment]
Elinize sağlık :)
