### ISSUE TITLE
İki ayrı note

### ISSUE THREAD

**Issue by yilmazm** [eminfedar/widgetci#5]
İki tane not kullanmak istedim. Bu yüzden widgets dizinindeki Note dizinini kopyalayıp ismini Program yaptım. Ardından ikisine farklı şeyler yazdım. Fakat bilgisayar kapatılıp açılınca ve ya widgetleri yenileyince iki ayrı not widgeti aynı şeyleri (en son hangsinde değişiklik yaptıysam onu) gösteriyor.

**Comment by eminfedar** [comment]
Widgetin klasörünü kopyaladıktan sonra içindeki **main.qml** dosyasındaki **appName** değişkenini yeni widgetinizin ismiyle değiştirmeyi unutmayın (bu isme göre klasör kaydı yapılıyor).

Çünkü Widgetcinin sağladığı **WFile** elementi ile dosya yazma&okuma gerçekleştiği için, dosyanın kaydedileceği yolu da parametre olarak vermeniz gerek.

Bunun için ise sadece widget adını yazmanız yeterli. Eğer widget klasörü dışında bir yerde dosya okumak isterseniz ise
- **readFileAnywhere(“dosyaYolu”)** ve yazmak için ise 
- **saveFileAnywhere(“dosyaYolu”, “verileriniz”)** ile yapabilirsiniz.

Note uygulaması ise direk widgetin klasörü içinde kayıt yaptığı için 
- **readFile(“wigdetAdi”, “dosyaAdi”)** ile çalışıyor.

bu yüzden widget adını ilk parametre olarak vermeyi unutmayın :+1:  :)

**Comment by yilmazm** [comment]
Teşekkür ederim, yeni notumun widgetName'ni değiştirince dediğiniz gibi düzeldi :) 
Bir başka güncellemede uygulama arayüzünden yeni widget'ler eklemeyi de yaparsınız muhtemelen :D
