### ISSUE TITLE
Bilgisayarı açınca widgetlerin otomatik gelmemesi

### ISSUE THREAD

**Issue by yilmazm** [eminfedar/widgetci#7]
Bilgisayarı açınca widgetler otomatik gelmedi, sağ altta widgetcinin simgesinden açıp widgetleri tek tek açmam gerekti. konumları ve kilitli olma durumları benim bıraktığım gibi.

**Comment by eminfedar** [comment]
Widgetin durumunun nadir olarak kaydedilmesinden kaynaklanıyor.
Şuan sadece belirli durumlarda widgetin durumu ve özellikleri kaydediliyor, bu sorunu ben de kullanırken fark ettim kullanıcının kullanım rahatlığını bozan bir şey.

Bir sonraki güncellemede bunu düzeltecek bir şeyler yapacağım :) :+1:

**Comment by yilmazm** [comment]
2 not ve saati kullanıyorum. Fakat bilgisayarı tekrar açınca hepsi gelmeyebiliyor. Tekrar açıyorum. Bazen bir not geliyor. Bazen 2 not geliyor. Bazen saat. Yani sürekli olarak son hali gelmiyor.
