### ISSUE TITLE
This application failed to start

### ISSUE THREAD

**Issue by ahmethakanbesel** [eminfedar/widgetci#8]
This application failed to start because it could not find or load Qt platform plugin "windows" in "".
![image](https://user-images.githubusercontent.com/6422460/35482369-1d502076-0445-11e8-94b8-f65a534950ff.png)

**Comment by yilmazm** [comment]
Aynısı bende de oldu

**Comment by eminfedar** [comment]
**qwindows.dll eklendi.**

Tekrar indirip açmayı deneyin: https://github.com/eminfedar/widgetci/releases/download/v1.0.2/widgetci_1.0.2_win32.rar
