### ISSUE TITLE
QtQuick is not installed

### ISSUE THREAD

**Issue by ahmethakanbesel** [eminfedar/widgetci#9]
Herhangi bir widget'ı etkinleştirmeye çalıştığımda "QtQuick is not installed" hatası alıyorum. Ayrıca widget listesinde bulunan switchlar çalışmıyor.
Sistem: Windows 10 PRO 1709 x64
![image](https://user-images.githubusercontent.com/6422460/35678443-7a55f1ca-0764-11e8-9b33-e84e72794c0d.png)

**Comment by eminfedar** [comment]
Widgetci'nin bulunduğu klasöre QtQuick.2 klasörünü kopyalayınca çözülmesi gerek, bir deneyin: 
[QtQuick.2.zip](https://github.com/eminfedar/widgetci/files/1686258/QtQuick.2.zip)

Eğer sorun çözülürse ve geri bildirim yaparsanız, issue çözüldü olarak işaretlenip kapatılır. :)

Geri bildirimleriniz için çok teşekkürler, uygulamayı Windows tarafında pek test edemedim :)

**Comment by ahmethakanbesel** [comment]
Sorun çözüldü.
